name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

  build-push-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
          aws configure set region us-east-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker Image
        run: docker build -t log-api .

      - name: Tag Docker Image
        run: docker tag log-api:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/log-api:latest

      - name: Push Docker Image to ECR
        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/log-api:latest
      
  deploy:
    runs-on: ubuntu-latest
    needs: build-push-image
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set Environment Variables
        run: |
          echo "TF_VAR_db_host=${{ secrets.TF_DB_HOST }}" >> $GITHUB_ENV
          echo "TF_VAR_db_user=${{ secrets.TF_DB_USER }}" >> $GITHUB_ENV
          echo "TF_VAR_db_password=${{ secrets.TF_DB_PASS }}" >> $GITHUB_ENV
          echo "TF_VAR_db_name=${{ secrets.TF_DB_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_db_port=${{ secrets.TF_DB_PORT }}" >> $GITHUB_ENV
          echo "TF_VAR_port=${{ secrets.TF_PORT }}" >> $GITHUB_ENV

      - name: Deploy Infrastructure Using Terraform
        run: |
          echo "Current Directory:"
          pwd
          tree
          echo "Listing Files:"
          ls -lah
          echo "Changing to terraform directory..."
          cd terraform || exit 1
          ls -lah
          cd terraform
          terraform init
          terraform apply -auto-approve
